name: Deploy Backend
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet build ./backend/Azure.AI.WebAccessibilityTool.API/AzureAI.WebAccessibilityTool.API.csproj --configuration Release
      
    - name: Publish
      run: dotnet publish ./backend/Azure.AI.WebAccessibilityTool.API/AzureAI.WebAccessibilityTool.API.csproj -c Release -o ./publish      

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'web-accessibility-api' # App Service name
        package: ./publish
