name: Deploy Backend
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Build
      run: dotnet build ./backend/WebAccessibility.Api/WebAccessibility.Api.csproj
    - name: Deploy to Azure
      run: |
        az webapp deploy --resource-group website-accessibility \
                        --name web-accessibility-api \
                        --src-path ./backend/WebAccessibility.Api/bin/Release/net8.0/publish
