name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - uses: actions/checkout@v3

      # Instalação do Node.js (Node 18)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instalação das dependências no diretório correto
      - name: Install dependencies
        run: npm install
        working-directory: frontend/web-accessibility-app

      # Build do projeto com variáveis de ambiente
      - name: Build
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          npm run build
        working-directory: frontend/web-accessibility-app
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      # Login no Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy para Static Web App
      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEBAPP_TOKEN }}
          app_location: "frontend/web-accessibility-app" 
          output_location: "build"                      
          deployment_action: "upload"
